const BASE_SPEED_FPS = 30;
export const FPS = 30;
export const BALL_SPEED = -10 * (BASE_SPEED_FPS / FPS); //15
export const BAT_SPEED = 15 * (BASE_SPEED_FPS / FPS);
export const BALL_H = 1;
export const BALL_V = 1;
export const TEXT_WIDTH = 1;
export const BAT_H = 0.5;
export const BAT_V = 28 / 5;
export const BORDER_H = 0.5;
export const BORDER_V = 6 / 5;
export const SCALE = 20;
export const DEBUG_MODE = false;
export const DEBUG_BALL = true;
